# Pimcore
pimcore_admin:

    session:
        attribute_bags:
            - pimcore_admin
            - pimcore_objects
            - pimcore_copy
            - pimcore_gridconfig
            - pimcore_importconfig

    # the following routes won't be double checked for authentication
    # this usually applies to login routes
    unauthenticated_routes:
        - { route: pimcore_settings_display_custom_logo }
        - { route: pimcore_admin_login }
        - { route: pimcore_admin_webdav }

    translations:
        path: "@PimcoreCoreBundle/translations"

# adds support for admin related routes that will be used to determine the request context in PimcoreContextGuesser
pimcore:
    context:
        admin:
            routes:
                - { path: ^/admin(/.*)?$ }
                - { route: ^pimcore_admin_ }